export enum SupportedCurrency {
    XPNET = 'XPNET',
    EGLD = 'EGLD',
    HT = 'HT',
    BNB = 'BNB',
    ETH = 'ETH',
    AVAX = 'AVAX',
    MATIC = 'MATIC',
    FTM = 'FTM',
    ONE = 'ONE',
    TRX = 'TRX',
    CELO = 'CELO',
    ONT = 'ONT',
    STAKE = 'STAKE',
    ALGO = 'ALGO',
    FUSE = 'FUSE',
    OPL = 'OPL',
    XTZ = 'XTZ',
    VLX = 'VLX',
    IOTX = 'IOTX',
    AURORA = 'ETH',
}
